#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
# . (period/dot) is prohibited in monitor names, so
# it must be escaped by prefixing the whole name with %
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

GRAY="#2D293B"
bspc config normal_border_color $GRAY

FLAMINGO='#ECBFBD'
bspc config focused_border_color $FLAMINGO
