#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

GRAY="#504945"
bspc config normal_border_color $GRAY

LIGHTER_GRAY='#928374'
bspc config focused_border_color $LIGHTER_GRAY

bspc rule -a Screenkey manage=off
