#!/usr/bin/env bash
#
# Attach or create tmux session named the same as current directory

session_name="$(basename "$PWD" | tr . -)"

session_exists() {
	tmux has-session -t "$session_name" 2>/dev/null
}

in_tmux() {
	[ -n "$TMUX" ]
}

create_detached_session() {
	(TMUX= tmux new-session -Ad -s "$session_name" -e "SESSION_DIR=$PWD")
}

if ! in_tmux; then
	tmux new-session -As "$session_name" -e "SESSION_DIR=$PWD"
else
	if ! session_exists; then
		create_detached_session
	fi

	tmux switch-client -t "$session_name"
fi
